#!/bin/sh
#
# Copyright © 2001 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

# Workfile:@(#)build_samples.sh	1.3
# Version:1.3
# Modified:03/26/01 13:37:49
# Original author: Oleg Danilov

 if [ "$JAVA_HOME" = "" ]; then
  echo Set environment variable JAVA_HOME
  exit
 fi

 if [ "$1" = "help" -o "$1" = "-help" ]; then
	echo "Usage: build_samples [options]"
	echo "Where options include:"
	echo "       -help     print out this message"
	echo "       -clean    remove all produced files"
	echo
	exit
 fi

 cd `/bin/dirname $0`/..
 JC21_HOME=${JC21_HOME:-`pwd`}

 cd $JC21_HOME/samples

# Clean

 if [ -d classes ]; then rm -r -f classes; fi
 if [ -f src/demo/*.txt ]; then rm src/demo/*.txt; fi
 if [ -f src/demo/demo2.scr ]; then rm src/demo/demo2.scr; fi
 if [ -f src/demo/JavaLoyalty.scr ]; then rm src/demo/JavaLoyalty.scr; fi
 if [ -f src/demo/JavaPurse.scr ]; then rm src/demo/JavaPurse.scr; fi
 if [ -f src/demo/SampleLibrary.scr ]; then rm src/demo/SampleLibrary.scr; fi
 if [ -f src/demo/Wallet.scr ]; then rm src/demo/Wallet.scr; fi

 if [ "$1" = "clean" -o "$1" = "-clean" ]; then exit; fi

 JC_PATH=".:$JC21_HOME/samples/classes"
 JCFLAGS="-g -d $JC21_HOME/samples/classes -classpath $JC_PATH"

# Extract classes from api21.jar

 mkdir classes
 cd classes
 $JAVA_HOME/bin/jar -xvf $JC21_HOME/lib/api21.jar
 rm -r -f META-INF
 cd ..

# Copy export files

 cp -r $JC21_HOME/api21_export_files/* classes/

# Compile samples

 $JAVA_HOME/bin/javac $JCFLAGS src/com/sun/javacard/samples/HelloWorld/*.java
 $JAVA_HOME/bin/javac $JCFLAGS src/com/sun/javacard/samples/SampleLibrary/*.java
 $JAVA_HOME/bin/javac $JCFLAGS src/com/sun/javacard/samples/JavaLoyalty/*.java
 $JAVA_HOME/bin/javac $JCFLAGS src/com/sun/javacard/samples/JavaPurse/*.java
 $JAVA_HOME/bin/javac $JCFLAGS src/com/sun/javacard/samples/NullApp/*.java
 $JAVA_HOME/bin/javac $JCFLAGS src/com/sun/javacard/samples/wallet/*.java

# Convert samples

 cd classes
 $JC21_HOME/bin/converter -config ../src/com/sun/javacard/samples/HelloWorld/HelloWorld.opt
 $JC21_HOME/bin/converter -config ../src/com/sun/javacard/samples/SampleLibrary/SampleLibrary.opt
 $JC21_HOME/bin/converter -config ../src/com/sun/javacard/samples/JavaLoyalty/JavaLoyalty.opt
 $JC21_HOME/bin/converter -config ../src/com/sun/javacard/samples/JavaPurse/JavaPurse.opt
 $JC21_HOME/bin/converter -config ../src/com/sun/javacard/samples/NullApp/NullApp.opt
 $JC21_HOME/bin/converter -config ../src/com/sun/javacard/samples/wallet/Wallet.opt
 cd ..

# Create SCR for demo2 in cref mode

 cd src/demo
 $JC21_HOME/bin/scriptgen -o JavaLoyalty.scr ../../classes/com/sun/javacard/samples/JavaLoyalty/javacard/JavaLoyalty.cap
 $JC21_HOME/bin/scriptgen -o JavaPurse.scr ../../classes/com/sun/javacard/samples/JavaPurse/javacard/JavaPurse.cap
 $JC21_HOME/bin/scriptgen -o SampleLibrary.scr ../../classes/com/sun/javacard/samples/SampleLibrary/javacard/SampleLibrary.cap
 $JC21_HOME/bin/scriptgen -o Wallet.scr ../../classes/com/sun/javacard/samples/wallet/javacard/wallet.cap
 cat Header.scr SampleLibrary.scr JavaLoyalty.scr JavaPurse.scr Wallet.scr AppletTest.scr Footer.scr > demo2.scr
 cd ../..
 exit
