<#import "generals.ftl" as tools>
${interface.package}.applet;

import javacard.framework.APDU;
import javacard.framework.ISO7816;
import javacard.framework.ISOException;

/**
 * This class represent a class generated by the applet generator
 *	
 */
public class ${interface.simpleName}Applet extends javacard.framework.Applet {

	/**
	 * This applet is designed to respond to the following
	 * class of instructions.
	 */
	final static byte ${interface.simpleName}AppletCLA = (byte)${interface.appletCLA};
	// This buffer represent the data to be send to the proxy
	private byte[] outBuffer;
	// Index in the outBuffer
	private short outBufferIndex;
	
	//Instruction set for ${interface.simpleName}Applet
	private final static byte GETRESULT = 0x7F;
	<#list interface.getDeclaredMethods() as method>
	private final static byte ${method.name?upper_case} = 0x${interface.instructionsNumber[method_index]};
	</#list>
	
	private static ${interface.simpleName}InterfaceApplet appletInterface;
	//TODO : déclarer ici les attributs de la classe
	
	/**
	 * Constructor for the applet
	 * @param buffer buffer
	 * @param offset offset
	 * @param length length
	 */
	private ${interface.simpleName}Applet(byte buffer[],short offset,byte length) {
		
		 appletInterface = new ${interface.simpleName}InterfaceApplet();
		 outBuffer = new byte[128];
		
		if (buffer[offset] == (byte)0) {
			register();
		}
		else {
			register(buffer, (short)(offset+1) ,(byte)(buffer[offset]));
		}
	}

	//  Every applet running JavaCard 2.0 must implement the following
	//  three functions.
	/**
	 *  You create the one instance of your applet here.
	 */ 
	public static void install(byte buffer[],short offset,byte length) {
		new ${interface.simpleName}Applet(buffer, offset, length);
	}

	/**
	 *  This function is called when your applet is selected.
	 */ 
	public boolean select() {
		return true;
	}

	/**
	 *  The process method dispatches messages to your class methods
	 *  depending on the instruction type.
	 */
	public void process(APDU apdu) throws ISOException{

		byte buffer[] = apdu.getBuffer();

        // Implement a select handler 
        if (selectingApplet()) {
            ISOException.throwIt(ISO7816.SW_NO_ERROR);
		}
		
		if (buffer[ISO7816.OFFSET_CLA] != ${interface.simpleName}AppletCLA) 
				ISOException.throwIt(ISO7816.SW_CLA_NOT_SUPPORTED);
    
        byte ins = buffer[ISO7816.OFFSET_INS];
        
		switch (ins) {
		case GETRESULT :
			sendRESULT(apdu);
			break; 
	<#list interface.getDeclaredMethods() as method>
		case ${method.name?upper_case} :
			${method.name}(apdu);
			break; 
	</#list>
		default:
			ISOException.throwIt(ISO7816.SW_INS_NOT_SUPPORTED);
		}
	}

	<#list interface.getDeclaredMethods() as method>
	private void ${method.name}(APDU apdu){
		//In buffer
		byte inBuffer[] = apdu.getBuffer();
		apdu.setIncomingAndReceive();
		//Set the index to the start of data buffer
		outBufferIndex = (short)(ISO7816.OFFSET_CDATA);
		<#list method.getParameterTypes() as type>
		<@tools.selectGetterType type=type index=type_index/>
		</#list>
		<#if method.getReturnType().toString()!="void">
		//Call the method
		${method.returnType} result = appletInterface.${method.name}(<#list method.getParameterTypes() as type><@tools.selectCallArgType type=type index=type_index has_next=type_has_next/></#list>);
		outBufferIndex=0;
		//Set the return type
		set${method.returnType?cap_first}(result);
		sendRESULTINFO(apdu);
		<#else>
		//Simply call method
		appletInterface.${method.name}(<#list method.getParameterTypes() as type>arg_${type_index}<#if type_has_next>,</#if></#list>);
		</#if>
		outBufferIndex=0;
	}
	</#list>
	
	/**
	* Send the result information about CALL
	*
	*/
	private void sendRESULTINFO(APDU apdu)
	{
			ISOException.throwIt((short)(0x6200 + outBufferIndex));
	}
	
	/**
	* Send the result information about CALL
	*
	*/
	private void sendRESULT(APDU apdu)
	{
		byte buffer[] = apdu.getBuffer();

		short numBytes = apdu.setIncomingAndReceive();

		if (numBytes != outBufferIndex) {
			ISOException.throwIt((short)ISO7816.SW_WRONG_LENGTH);
		}

		apdu.setOutgoing();
		apdu.setOutgoingLength(numBytes);
		
		for (short index = 0; index < numBytes; index++) 
			buffer[index] = outBuffer[index];

		apdu.sendBytes((short)0,(short)numBytes);

		return;
	}
<@tools.utils/>
}
