<#import "generals.ftl" as tools>
${interface.package}.applet;

import javacard.framework.APDU;
import javacard.framework.ISO7816;
import javacard.framework.ISOException;

/**
 * This class represent a class generated by the applet generator
 *	
 */
public class ${interface.simpleName}InterfaceApplet {
	
	//TODO : Ecrire le attribut de classe ici
	
	<#list interface.getDeclaredMethods() as method>
	/**
	*
	<#list method.getParameterTypes() as type>* @param ${type} arg_${type_index}</#list>
	*/
	public ${method.returnType} ${method.name}(<#list method.getParameterTypes() as type><@tools.selectArgType type=type index=type_index has_next=type_has_next/></#list>)
	{	
		//TODO : implémenter la méthode ici
		<#if method.getReturnType().toString()!="void">
		return 0;
		</#if>
	}
	</#list>
}
